## MNIST Dataset Example

Loading the MNIST dataset in Keras

In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 4s 0us/step


The images are encoded as numpy arrays, and the labels are an array of digits, from 0 to 9

Training data

In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Testing data

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

The network architecture

In [11]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

The compilation step

In [19]:
model.compile(optimizer='rmsprop',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Preparing the image data

In [15]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

Training the model

In [20]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 14ms/step - loss: 1.4515 - accuracy: 0.6722
Epoch 2/5
469/469 [==============================] - 7s 16ms/step - loss: 0.5749 - accuracy: 0.8549
Epoch 3/5
469/469 [==============================] - 7s 15ms/step - loss: 0.4065 - accuracy: 0.8899
Epoch 4/5
469/469 [==============================] - 7s 15ms/step - loss: 0.3503 - accuracy: 0.9020 0s - loss: 0.3514 - 
Epoch 5/5
469/469 [==============================] - 7s 15ms/step - loss: 0.3213 - accuracy: 0.9090 0s - loss: 0.3


Using the model to make predictions

In [22]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [23]:
predictions[0].argmax()

7

In [25]:
predictions[0][7]

1.0

In [26]:
test_labels[0]

7

Evaluating the model on new data

In [27]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 55.3710 - accuracy: 0.8164


In [28]:
print(f'test acc = {test_acc}')

test acc = 0.8163999915122986
